spring:
  data:
    mongodb:
      host: 192.168.100.28
      port: 27017
      database: chenkuo
      username: root
      password: 123456
      sxbgColletion: sxbg
      sdbgColletion: sdbg
      creditCollection: sxbg
      reviewCollection: sdbg